### ISSUE TITLE
Windows 10 compatibility

### ISSUE THREAD

**Issue by wlastpaw** [novakin/Kitty-Session-Manager#1]
Hi Novakin!

Great that You have made Kitty Session Manager available. I wanted to use it on windows 10 and all I can manage is small window with directory "Sessions" where I have no possibility to create proper sessions. 
May this be compatibility issue? Or I doing something wrong?

Help would be very appreciated
![kitty_sessionmanagerissueprint](https://user-images.githubusercontent.com/17765659/36392423-62045486-15ab-11e8-95f4-a0c3a0969470.jpg)

**Comment by novakin** [comment]
Hi, 

Have you tried to refresh the sessions using the tray icon menu ?  You'll also be able to create sessions. 
![image](https://user-images.githubusercontent.com/10003175/36392489-840d0f6c-15bc-11e8-8f6e-267b620df291.png)

**Comment by novakin** [comment]
I'll close the issue, re-open it if you still have troubles
